name: Release

on:
  release:
    types: [created]  # Trigger when a new release is created

jobs:
  build:
    name: Build and Upload glcm cli
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: '${{ env.GOPATH }}/src/github.com/${{ github.repository }}'
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.7
          cache: false

      - name: Build cli
        run: |
          cd ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/glcm-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/glcm-darwin-arm64 .


      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/glcm-linux-amd64
            dist/glcm-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
